# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/executor.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/executor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14proto/executor.proto\x12\x08\x65xecutor\"\xa8\x01\n\x0e\x45xecuteRequest\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x36\n\x07\x63ontext\x18\x02 \x03(\x0b\x32%.executor.ExecuteRequest.ContextEntry\x12\x0f\n\x07timeout\x18\x03 \x01(\x05\x1a?\n\x0c\x43ontextEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1e\n\x05value\x18\x02 \x01(\x0b\x32\x0f.executor.Value:\x02\x38\x01\"`\n\x0f\x45xecuteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x1f\n\x06result\x18\x02 \x01(\x0b\x32\x0f.executor.Value\x12\r\n\x05\x65rror\x18\x03 \x01(\t\x12\x0c\n\x04logs\x18\x04 \x03(\t\"\x97\x02\n\x05Value\x12\x13\n\tstr_value\x18\x01 \x01(\tH\x00\x12\x13\n\tint_value\x18\x02 \x01(\x03H\x00\x12\x15\n\x0b\x66loat_value\x18\x03 \x01(\x01H\x00\x12\x14\n\nbool_value\x18\x04 \x01(\x08H\x00\x12)\n\nnull_value\x18\x05 \x01(\x0e\x32\x13.executor.NullValueH\x00\x12)\n\nlist_value\x18\x06 \x01(\x0b\x32\x13.executor.ListValueH\x00\x12%\n\tmap_value\x18\x07 \x01(\x0b\x32\x10.executor.StructH\x00\x12\x31\n\x0e\x66unction_value\x18\x08 \x01(\x0b\x32\x17.executor.FunctionValueH\x00\x42\x07\n\x05value\",\n\tListValue\x12\x1f\n\x06values\x18\x01 \x03(\x0b\x32\x0f.executor.Value\"v\n\x06Struct\x12,\n\x06\x66ields\x18\x01 \x03(\x0b\x32\x1c.executor.Struct.FieldsEntry\x1a>\n\x0b\x46ieldsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1e\n\x05value\x18\x02 \x01(\x0b\x32\x0f.executor.Value:\x02\x38\x01\"\x1d\n\rFunctionValue\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x0f\n\rHealthRequest\"2\n\x0eHealthResponse\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\x12\x0f\n\x07version\x18\x02 \x01(\t*\x1b\n\tNullValue\x12\x0e\n\nNULL_VALUE\x10\x00\x32\x8d\x01\n\x0ePythonExecutor\x12>\n\x07\x45xecute\x12\x18.executor.ExecuteRequest\x1a\x19.executor.ExecuteResponse\x12;\n\x06Health\x12\x17.executor.HealthRequest\x1a\x18.executor.HealthResponseB\rZ\x0bmemci/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.executor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\013memci/proto'
  _globals['_EXECUTEREQUEST_CONTEXTENTRY']._loaded_options = None
  _globals['_EXECUTEREQUEST_CONTEXTENTRY']._serialized_options = b'8\001'
  _globals['_STRUCT_FIELDSENTRY']._loaded_options = None
  _globals['_STRUCT_FIELDSENTRY']._serialized_options = b'8\001'
  _globals['_NULLVALUE']._serialized_start=851
  _globals['_NULLVALUE']._serialized_end=878
  _globals['_EXECUTEREQUEST']._serialized_start=35
  _globals['_EXECUTEREQUEST']._serialized_end=203
  _globals['_EXECUTEREQUEST_CONTEXTENTRY']._serialized_start=140
  _globals['_EXECUTEREQUEST_CONTEXTENTRY']._serialized_end=203
  _globals['_EXECUTERESPONSE']._serialized_start=205
  _globals['_EXECUTERESPONSE']._serialized_end=301
  _globals['_VALUE']._serialized_start=304
  _globals['_VALUE']._serialized_end=583
  _globals['_LISTVALUE']._serialized_start=585
  _globals['_LISTVALUE']._serialized_end=629
  _globals['_STRUCT']._serialized_start=631
  _globals['_STRUCT']._serialized_end=749
  _globals['_STRUCT_FIELDSENTRY']._serialized_start=687
  _globals['_STRUCT_FIELDSENTRY']._serialized_end=749
  _globals['_FUNCTIONVALUE']._serialized_start=751
  _globals['_FUNCTIONVALUE']._serialized_end=780
  _globals['_HEALTHREQUEST']._serialized_start=782
  _globals['_HEALTHREQUEST']._serialized_end=797
  _globals['_HEALTHRESPONSE']._serialized_start=799
  _globals['_HEALTHRESPONSE']._serialized_end=849
  _globals['_PYTHONEXECUTOR']._serialized_start=881
  _globals['_PYTHONEXECUTOR']._serialized_end=1022
# @@protoc_insertion_point(module_scope)
